export const globalStyles = {
  flexRowSA: {
    padding: '10px',
    display: 'flex',
    flexDirection: 'row',
    textAlign: 'center',
    justifyContent: 'space-around',
    border: '1px solid grey',
  },
  flexCol: {
    padding: '10px',
    display: 'flex',
    flexDirection: 'column',
    textAlign: 'center',
    justifyContent: 'space-around',
    border: '1px solid grey',
  },
  container: {
    padding: '13px',
    display: 'flex',
    flexDirection: 'column',
    textAlign: 'center',
  },
  border: {
    border: '1px solid grey',
  },

  button: {
    backgroundColor: '#fbeee0',
    border: '2px solid #422800',
    borderRadius: '30px',
    boxShadow: '#422800 4px 4px 0 0',
    color: '#422800',
    cursor: 'pointer',
    display: 'inline-block',
    fontWeight: 600,
    fontSize: '18px',
    padding: '0 18px',
    lineHeight: '50px',
    textAlign: 'center',
    textDecoration: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    touchAction: 'manipulation',
  },
};
